theme: jekyll-theme-cayman

title: "Alzheimer's Analysis"
subtitle: ["Blood-based Analysis of Alzheimer's Disease from miRNA Data"]
#description: ["Ryan Cummings, Justin Kang, Gregory Thein DSC 180B WI21" ]
description: ["Ryan Cummings, Justin Kang, Gregory Thein<br>DSC 180B B04-Genetics WI21"]
# description: ["DSC 180B WI21"]
