theme: jekyll-theme-cayman

title: [Alzheimer's Disease Blood Analysis]
#description: ["Ryan Cummings, Justin Kang, Gregory Thein DSC 180B WI21" ]
description: [ Ryan Cummings,&ensp;Justin Kang,&ensp;Gregory Thein<br>DSC 180B WI21"]
# description: ["DSC 180B WI21"]
